modLoader="javafml"
loaderVersion="${forge_version_range}"
license="MIT"

[[mods]]
modId="sophisticated_jei_index"
version="${mod_version}"
displayName="Sophisticated JEI Index"
logoFile="logo.png"
description='''${mod_description}'''
credits="JEI recipe transfer integration for Sophisticated Backpacks"
authors="amicbeam"

[[dependencies.sophisticated_jei_index]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="sophisticatedbackpacks"
mandatory=true
versionRange="[3.24,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="jei"
mandatory=false
versionRange="[15.0,)"
ordering="AFTER"
side="BOTH"
