modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="sophisticated_jei_index"
version="1.0.2"
displayName="Sophisticated JEI Index"
logoFile="logo.png"
description='''JEI Index Upgrade for Sophisticated Backpacks. When installed, allows JEI recipe transfer to use items from equipped backpacks that have this upgrade.'''
credits="JEI recipe transfer integration for Sophisticated Backpacks"
authors="amicbeam"

[[mixins]]
config="sophisticated_jei_index.mixins.json"

[[mixins]]
config="sophisticated_jei_index.emi.mixins.json"

[[mixins]]
config="sophisticated_jei_index.ae2.mixins.json"

[[mixins]]
config="sophisticated_jei_index.rs.mixins.json"

[[dependencies.sophisticated_jei_index]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="sophisticatedbackpacks"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="jei"
type="required"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="emi"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="ae2"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.sophisticated_jei_index]]
modId="refinedstorage"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
